import { HexTile } from '../types/hex.types';
import { starterBoardPreset } from './starterBoardPreset';

export const seafarersNewShoresPreset: HexTile[] = [
  ...starterBoardPreset,
  {
    id: 'hex_20',
    coord: { q: -3, r: 0, s: 3 },
    type: 'WATER',
    numberToken: null,
    hasRobber: false,
  },
  {
    id: 'hex_21',
    coord: { q: -3, r: 1, s: 2 },
    type: 'GOLD_FIELD',
    numberToken: 4,
    hasRobber: false,
  },
  {
    id: 'hex_22',
    coord: { q: -3, r: 2, s: 1 },
    type: 'GOLD_FIELD',
    numberToken: 10,
    hasRobber: false,
  },
  {
    id: 'hex_23',
    coord: { q: -3, r: 3, s: 0 },
    type: 'WATER',
    numberToken: null,
    hasRobber: false,
  },
  {
    id: 'hex_24',
    coord: { q: -2, r: 3, s: -1 },
    type: 'WOOD',
    numberToken: 8,
    hasRobber: false,
  },
  {
    id: 'hex_25',
    coord: { q: -1, r: 3, s: -2 },
    type: 'WATER',
    numberToken: null,
    hasRobber: false,
  },
  {
    id: 'hex_26',
    coord: { q: 0, r: 3, s: -3 },
    type: 'SHEEP',
    numberToken: 9,
    hasRobber: false,
  },
  {
    id: 'hex_27',
    coord: { q: 1, r: 2, s: -3 },
    type: 'WATER',
    numberToken: null,
    hasRobber: false,
  },
  {
    id: 'hex_28',
    coord: { q: 2, r: 1, s: -3 },
    type: 'BRICK',
    numberToken: 5,
    hasRobber: false,
  },
  {
    id: 'hex_29',
    coord: { q: 3, r: 0, s: -3 },
    type: 'WATER',
    numberToken: null,
    hasRobber: false,
  },
  {
    id: 'hex_30',
    coord: { q: 3, r: -1, s: -2 },
    type: 'GOLD_FIELD',
    numberToken: 6,
    hasRobber: false,
  },
  {
    id: 'hex_31',
    coord: { q: 3, r: -2, s: -1 },
    type: 'GOLD_FIELD',
    numberToken: 8,
    hasRobber: false,
  },
  {
    id: 'hex_32',
    coord: { q: 3, r: -3, s: 0 },
    type: 'WATER',
    numberToken: null,
    hasRobber: false,
  },
  {
    id: 'hex_33',
    coord: { q: 2, r: -3, s: 1 },
    type: 'ORE',
    numberToken: 11,
    hasRobber: false,
  },
  {
    id: 'hex_34',
    coord: { q: 1, r: -3, s: 2 },
    type: 'WATER',
    numberToken: null,
    hasRobber: false,
  },
  {
    id: 'hex_35',
    coord: { q: 0, r: -3, s: 3 },
    type: 'WHEAT',
    numberToken: 3,
    hasRobber: false,
  },
  {
    id: 'hex_36',
    coord: { q: -1, r: -2, s: 3 },
    type: 'WATER',
    numberToken: null,
    hasRobber: false,
  },
  {
    id: 'hex_37',
    coord: { q: -2, r: -1, s: 3 },
    type: 'ORE',
    numberToken: 10,
    hasRobber: false,
  },
];
