import { HexTile } from '../types/hex.types';

export const starterBoardPreset: HexTile[] = [
  {
    id: 'hex_1',
    coord: { q: -2, r: 0, s: 2 },
    type: 'ORE',
    numberToken: 10,
    hasRobber: false,
  },
  {
    id: 'hex_2',
    coord: { q: -2, r: 1, s: 1 },
    type: 'SHEEP',
    numberToken: 2,
    hasRobber: false,
  },
  {
    id: 'hex_3',
    coord: { q: -2, r: 2, s: 0 },
    type: 'WOOD',
    numberToken: 9,
    hasRobber: false,
  },
  {
    id: 'hex_4',
    coord: { q: -1, r: -1, s: 2 },
    type: 'WHEAT',
    numberToken: 12,
    hasRobber: false,
  },
  {
    id: 'hex_5',
    coord: { q: -1, r: 0, s: 1 },
    type: 'BRICK',
    numberToken: 6,
    hasRobber: false,
  },
  {
    id: 'hex_6',
    coord: { q: -1, r: 1, s: 0 },
    type: 'SHEEP',
    numberToken: 4,
    hasRobber: false,
  },
  {
    id: 'hex_7',
    coord: { q: -1, r: 2, s: -1 },
    type: 'BRICK',
    numberToken: 10,
    hasRobber: false,
  },
  {
    id: 'hex_8',
    coord: { q: 0, r: -2, s: 2 },
    type: 'WHEAT',
    numberToken: 9,
    hasRobber: false,
  },
  {
    id: 'hex_9',
    coord: { q: 0, r: -1, s: 1 },
    type: 'WOOD',
    numberToken: 11,
    hasRobber: false,
  },
  {
    id: 'hex_10',
    coord: { q: 0, r: 0, s: 0 },
    type: 'DESERT',
    numberToken: null,
    hasRobber: true,
  },
  {
    id: 'hex_11',
    coord: { q: 0, r: 1, s: -1 },
    type: 'WOOD',
    numberToken: 3,
    hasRobber: false,
  },
  {
    id: 'hex_12',
    coord: { q: 0, r: 2, s: -2 },
    type: 'ORE',
    numberToken: 8,
    hasRobber: false,
  },
  {
    id: 'hex_13',
    coord: { q: 1, r: -2, s: 1 },
    type: 'WOOD',
    numberToken: 8,
    hasRobber: false,
  },
  {
    id: 'hex_14',
    coord: { q: 1, r: -1, s: 0 },
    type: 'ORE',
    numberToken: 3,
    hasRobber: false,
  },
  {
    id: 'hex_15',
    coord: { q: 1, r: 0, s: -1 },
    type: 'WHEAT',
    numberToken: 4,
    hasRobber: false,
  },
  {
    id: 'hex_16',
    coord: { q: 1, r: 1, s: -2 },
    type: 'SHEEP',
    numberToken: 5,
    hasRobber: false,
  },
  {
    id: 'hex_17',
    coord: { q: 2, r: -2, s: 0 },
    type: 'BRICK',
    numberToken: 5,
    hasRobber: false,
  },
  {
    id: 'hex_18',
    coord: { q: 2, r: -1, s: -1 },
    type: 'WHEAT',
    numberToken: 6,
    hasRobber: false,
  },
  {
    id: 'hex_19',
    coord: { q: 2, r: 0, s: -2 },
    type: 'SHEEP',
    numberToken: 11,
    hasRobber: false,
  },
];
